### ISSUE TITLE
Generated Images Not Compresed

### ISSUE THREAD

**Issue by gabe565** [rissson/place-timelapse-2022#3]
Hello!

Great work on the scraper. Love seeing Rust used for this sort of thing.

I downloaded your dataset and noticed most of the images are uncompressed. I did a little bit of research into the `image` crate, and it looks like it doesn't support deflate. In this [GitHub issue](https://github.com/image-rs/image/issues/419), they created a separate [`png` crate](https://crates.io/crates/png) that adds support for it.

I recompressed all 15GB of images with `mogrify` and was able to drop the size down to 5.5GB. I'd understand not adding deflate support now that /r/place is over, but you could save a lot of storage space if you recompress the data you have!

**Comment by rissson** [comment]
I actually wanted to do something that indeed compresses this data (in #2) for #1, but now that r/place is over, I kinda lost interest. Might still work on it in the future, especially since I want to try out yew/seed.
For now I'm going to close this and will probably run mogrify on the data I already have. Do you mind sharing the command you ran?

**Comment by gabe565** [comment]
Sounds good to me, thanks!

Sure! Mogrify compresses by default, meaning you can run it without any flags and it will compress all images:
```shell
mogrify -monitor *.png
```
Problem is, mogrify doesn't run in parallel, making the conversion take much longer than it should. To speed it up, I used the parallel command:
```shell
parallel mogrify -monitor -- *.png
```
(You'll need to install both `imagemagick` and `parallel` for these)

Let me know if you come across any issues!
